### ISSUE TITLE
Hello, World: Pass listening port in YAML config

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-project.github.io#9]
I try to streamline the *Hello, World* tutorial and remove as many preparation steps as possible. For example, I want to reuse an existing image off DockerHub instead of having to create my own.

However, the NodeJS code currently has the listening port number hardcoded. I can't thus reuse someone else's image because then I might hit their old deployed instance unknowingly.

A way around having to rebuild the Docker image for every experimenter could be to supply the listening port through the YAML config: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

This should allow us to start the NodeJS server inside the Docker image with per-experimenter config from the YAML, i.e. a single image will do for everyone taking the tutorial.

**Comment by aaaaalbert** [comment]
A Python2 version of the echo server is available from my fork of this repo, https://github.com/aaaaalbert/edgenet-project.github.io/blob/simpler-hello-world/assets/other/echo_server.py .

It takes the listening port as a command line argument.

**Comment by aaaaalbert** [comment]
Alternatively and perhaps even simpler, the server inside the container can run on and expose via the `Dockerfile` its default port (8000 in my case), and we use Kubernetes to forward *another* port to the one that the pod exposes.

I'm testing this in my "mini hello world" right now.

**Comment by aaaaalbert** [comment]
The [`expose` command of `kubectl`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#expose) seems to be a way to do just this.

Example:
```
kubectl --kubeconfig=sundew.cfg expose pod echo123-pvwgp --port=49134 --container-port=8000
```

**Comment by boldt** [comment]
I suggest creating a new organization called `edge-net` on https://hub.docker.com/ where you push the hello world example server. Wrt to my [docker-express-example](https://hub.docker.com/r/boldt/docker-express-example/), I use the following config:

```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
 name: docker-express-example
spec:
 template:
   metadata:
     labels:
       app: docker-express-example
   spec:
     containers:
       - name: docker-express-example
         image: boldt/docker-express-example:0.0.1
         ports:
         - containerPort: 3000
           hostPort: <randomPort>
```

Cant you just say: "Replace `<randomPort>` with a random port"?
